.TH TDU 1 "2020-06-10" "1.34" "Top Disk Usage manual"

.SH NAME
tdu \- get information about largest files and directories

.SH SYNOPSIS
 tdu [options] [directory]

.SH DESCRIPTION
tdu (Top Disk Usage) shows which directories and files are using your disk space.
.br
It is written in Go and is inspired by the well-known UNIX
.B du
command.
.PP
It scans recursively all subdirectories starting at <directory>
.br
or at current directory by default.

.SH FEATURES
* Counts files, directories, links, sockets, pipes.
.br
* Counts empty directories, denied accesses, errors.
.br
* Shows deepest directory path.
.br
* Shows longest file path.
.br
* Displays information about the filesystem (type, mount options, size, inodes).

.SH OPTIONS
.TP
.BI \-l \ n
Number of depth1 items shown (default 15)
.TP
.BI \-b \ n
Number of big files shown (default 7)
.TP
.BR \-\-max
Show deepest and longest paths (default no)
.TP
.BI \-e \ n
Number of empty directories shown (default 0)
.TP
.BI \-d \ n
Number of access denied directories shown (default 0)
.TP
.BI \-f \ n
Number of character and block devices shown (default 0)
.TP
.BI \-t \ n
Number of sockets and named pipes shown (default 0)
.TP
.BI \-s \ n
Number of file status errors shown (default 0)
.TP
.BR \-\-human
Print sizes in human readable format (default Kb only)
.TP
.BI \-o \ file
Export result to Ncdu JSON format
.br
(https://dev.yorhel.nl/ncdu/jsonfmt)
.TP
.BR \-\-version
Program info and usage
.TP
.BR \-\-license
Show the GNU General Public License V2
.TP
.BR \-\-help
Program help

.SH LIMITS
Does not cross filesystem boundaries. It behaves like
.B du \-skx

.SH COPYRIGHT
Copyright \(co 2019,2020 Joseph Paul <joseph.paul1@gmx.com>.
.br
License GPLv2+: GNU GPL version 2 or later.

.SH WEBSITE
https://bitbucket.org/josephpaul0/tdu

.SH "SEE ALSO"
.BR du (1),
.BR ncdu (1)

